spring.application.name=hospitalinventory

# DATABASE
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

spring.datasource.password=DIYA@2004
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_inventory_ai

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SERVER
server.port=8080

# AI SERVICE
#ai.service.url=${AI_SERVICE_URL}
ai.service.url=https://hospitalai-service.onrender.com/predict

# LOGGING
logging.level.org.springframework.web=DEBUG